### ISSUE TITLE
rust runtime error

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#240] opened 2023-02-07 08:07 UTC
this code crashes metta interpreter

```
from hyperon import *

def test():
        program = '''
(1 2)
(2 3)
(2 4)
(3 4)
(= (add $a) 
   (add-atom &self
                                    ($y $x)
   True)

!(println! (match &self (, ($x $y)
                           ($y $z)
                           ($y $w)
                           ($z $w))

                           (nop (process (add-atom &self
                                    ($y $x)))
                              (process (remove-atom &self
                                  ($x $y))))))
        '''
        runner = MeTTa()
        result = runner.run(program)

        print(runner.space().get_atoms())

test()
```

stacktrace:
[log.txt](https://github.com/trueagi-io/hyperon-experimental/files/10672827/log.txt)

**Comment by Necr0x0Der** [comment] 2023-02-07 08:24
There is missed parenthesis in your code :
``` 
(= (add $a) 
   (add-atom &self ($y $x)
   True)
```
I'm not sure what semantics you implied, but if you add closing parenthesis before or after `True`, it will not crash. The parser panics on incorrect programs. This is not a bug, although the behavior could be improved.

**Closed by Necr0x0Der** 2023-02-07 08:24 UTC
