### ISSUE TITLE
Unable to use variable type

### ISSUE THREAD

**Issue by tanksha** [trueagi-io/hyperon-experimental#274] opened 2023-04-13 21:22 UTC
The following code doesn't work

```scheme
(: ≞ (-> $event $tv Type))
(: TruthValue Type)
(: Bl (-> Bool TruthValue))
(≞ (P 42) (Bl True))

(= (idi_formula $r1 $r2)
   (Bl True))    

(= (idi_match $kb)
   (let* (($prem1 (≞ ($p $a) $patv))
          ($prem2 (≞ ($q $a) $qatv))) 
     (match $kb
       ;; Premises
       (, $prem1 $prem2)  
       ;; Conclusion
       (≞ (→ $p $q) (idi_formula $prem1 $prem2)))))

!(idi_match &self)
```

If I were to change `(: ≞ (-> $event $tv Type))`  by `(: ≞ (-> Atom Atom Type))`, I got the following result
`[(≞ (→ P P) (idi_formula (≞ (P 42) (Bl True)) (≞ (P 42) (Bl True))))]`
But, the `idi_formula` function doesn't get reduced.

**Comment by vsbogd** [comment] 2023-04-14 11:12
Quick workaround is using `(: ≞ (-> Atom $tv Type))` as a type. It gives `(: ≞ (-> $event $tv Type))` as a result.

**Comment by vsbogd** [comment] 2023-04-14 11:27
Proper fix looks similar to the content of the following `TODO` comment in code: https://github.com/trueagi-io/hyperon-experimental/blob/ee62ee8f0a25a4c653e8fad26dd996564ff6e557/lib/src/metta/types.rs#L178-L185

In the case above if pair `($p $a)` has type `($ptype $atype)` (instead of `%Undefined%` it has now), then interpreter would not try to execute the pair `($p $a)` as a function and code would work.

**Comment by vsbogd** [comment] 2023-04-14 15:04
Minimal example to reproduce:
```
(: ? (-> $P Type))
(= (foo $bar) (? ($a $b)))

!($y $z)
```

**Comment by vsbogd** [comment] 2023-04-14 15:16
Well, the trick with `($atype $btype)` doesn't work either because interpreter tries to match pair even when variable has a non-functional type.

**Comment by vsbogd** [comment] 2023-04-26 08:45
On the one hand restricting variables to match the operation as suggested in #242 resolves this issue as well. On the other hand I would prefer more general solution like #177 to resolve this.

**Comment by vsbogd** [comment] 2023-04-26 11:34
@Necr0x0Der , @tanksha , I propose closing it as a duplicate of #177, what do you think?

**Comment by Necr0x0Der** [comment] 2023-04-26 16:09
> @Necr0x0Der , @tanksha , I propose closing it as a duplicate of #177, what do you think?

Yes, it makes sense. But maybe it would be nice to copypast @tanksha example to #177 then?

**Comment by vsbogd** [comment] 2023-06-06 08:33
Closing as duplicate of #177

**Closed by vsbogd** 2023-06-06 08:33 UTC
