### ISSUE TITLE
Dockerfile is broken : extend-py! doesn't work . REPL cannot be compiled.

### ISSUE THREAD

**Issue by astroseger** [trueagi-io/hyperon-experimental#561] opened 2024-01-31 12:40 UTC
Dockerfile is broken. There are at least two critical issues:

1. extend-py! is completely broken 

In order to reproduce. Create a new directory. In this directory create a binding for (random) from  https://github.com/trueagi-io/hyperon-experimental/issues/553 and try to run the following metta script
```
!(extend-py! random_binding)
; random will be executed, a1 is associated with the result
!(bind! a1 (random))
```
It will fail with the following error:
```
[(Error (extend-py! random_binding) Exception caught:
RuntimeError: Failed to load module random_binding; could not locate file: random_binding/__init__.py

At:
  /home/user/hyperon-experimental/python/hyperon/runner.py(164): load_py_module_from_mod_or_file
  /home/user/hyperon-experimental/python/hyperon/runner.py(78): <lambda>
  /home/user/hyperon-experimental/python/hyperon/atoms.py(327): execute
  /home/user/hyperon-experimental/python/hyperon/atoms.py(174): _priv_call_execute_on_grounded_atom
  /home/user/hyperon-experimental/python/hyperon/runner.py(196): run
  /home/user/hyperon-experimental/python/hyperon/runner.py(188): import_file
  /home/user/hyperon-experimental/python/hyperon/metta.py(32): main
  /home/user/.local/bin/metta(8): <module>
)]

```

2. Compilation of REPL fails

cargo build in repl directory returns the following error:
```    
Updating crates.io index
Updating git repository `https://github.com/kkawakam/rustyline`
error: failed to select a version for the requirement `rustyline = "^12.0.0"`
candidate versions found which didn't match: 13.0.0
location searched: Git repository https://github.com/kkawakam/rustyline
required by package `metta-repl v0.1.0 (/home/user/hyperon-experimental/repl)`
```

**Comment by patham9** [comment] 2024-01-31 23:22
I can confirm, extend-py! is not working for Python files anymore unfortunately, which is a critical bug which also affects MeTTa-Morph.

**Comment by luketpeterson** [comment] 2024-02-01 06:29
The repl build is fixed in https://github.com/trueagi-io/hyperon-experimental/pull/566/  I haven't yet looked at the other things mentioned.

**Comment by vsbogd** [comment] 2024-02-01 14:25
@astroseger , does first part is a  duplicate of https://github.com/trueagi-io/hyperon-experimental/issues/547 ?

**Comment by patham9** [comment] 2024-02-01 19:23
As Hedra pointed out, the January 27 commits still support **extend-py!** properly. Maybe the diff to that date can be helpful for debugging the breakage that happened after.

**Comment by Necr0x0Der** [comment] 2024-02-01 19:36
@patham9 , could it be broken by this PR https://github.com/trueagi-io/hyperon-experimental/pull/555 ?
It is not directly related to Docker, and the idea was to separate cases of loading python modules via Python notation and importing Python files via their path. I'm not sure why direct import like `!(extend-py! random_binding)` should not work, because, say, `random_binding` should be imported in this case as a normal Python module, but Docker might be making some tricks with environments, which are not covered by the proposed code modification.
@astroseger , could you please try replacing
`!(extend-py! random_binding)` with `!(extend-py! random_binding.py)`?
and also try to replace
`mod_name.replace('.', os.sep) + os.sep + "__init__.py"`
back to
`mod_name.replace('.', os.sep) + ".py"`
in `hyperon/runner.py`?

**Comment by patham9** [comment] 2024-02-01 19:43
@Necr0x0Der Yes this PR is it, as it appends `__init__` there, it now expects the code file to have that name within a folder of the file. So instead of `name.py` this now looks for `name/__init__.py`.
Indeed using `!(extend-py! mettamorph.py)` makes it not do that, thank you for this workaround!
I am fine with adding `.py` from now one for single-file extensions and having it expect a folder instead when it is not appended.

**Comment by Necr0x0Der** [comment] 2024-02-01 19:50
Thanks for confirming @patham9 . It's completely unexpected for me that the module loading by a direct `import_module` fails for a .py file in the Docker while it doesn't fail in non-Docker environments. One possibility is that `.` is not added to `PYTHON_PATH` in the Docker, and this was worked around by the subsequent code. Could you check please that adding `.` to the Python path also fixes the problem?

**Comment by Necr0x0Der** [comment] 2024-02-01 19:54
In general, I'm OK with rolling back this part of #555 PR, although the idea was that imports supported by Python notation for modules are exactly the same imports which are supported by Python. So, if you are doing `(extend-py! random_binding)`, it should work in the same cases, as if you do `import random_binding` in the Python script in the same folder.
I wonder if `(extend-py! .random_binding)` (with `.` before random_binding) is also working now...

**Comment by patham9** [comment] 2024-02-01 20:00
Hm for me it was not a Docker issue, I ran on Mac OS Ventura and on Ubuntu 22 LTS, both showed this new issue.
And I can now confirm "." to PYTHONPATH worked in both cases!

**Comment by Necr0x0Der** [comment] 2024-02-01 20:09
> And I can now confirm "." to PYTHONPATH works in both cases!

Thanks for confirming again.
I believe that the current behavior is more consistent, but might be less convenient. Also, since @luketpeterson is close to introduce a new module system, which will have a different behavior and may not support this sort of behavior when `.py` is added (so, if you add `.py` now, it will not be needed to remove it later), I'm really OK with rolling back the change in #555 , which will remove the feature I wanted to introduce (but this can be sorted out after merging Luke's module system).
@patham9 , @astroseger , @tanksha, do you prefer to restore the previous behavior (which may or may not be supported by the upcoming module system), or is it ok for you to use `extend-py!` in the same way as Python's `import` (which may or may not be supported by the upcoming module system)?

**Comment by patham9** [comment] 2024-02-01 20:24
I would prefer the current solution with `.py` assuming it will also work in the future. The reason why I like it is that it is explicit about that a single Python file is imported, while when `.py` is missing we could generally use that to indicate a folder / module that is imported.

**Comment by vsbogd** [comment] 2024-02-02 03:26
> Hm for me it was not a Docker issue, I ran on Mac OS Ventura and on Ubuntu 22 LTS, both showed this new issue.

One source of the issue may be the fact that different Python packages uses different `sys.path` values. At least I faced this difference even between Ubuntu and Debian distributions.

**Comment by vsbogd** [comment] 2024-02-09 05:14
My understanding that root cause is clear and this issue will be outdated by the merge of the module system. https://github.com/trueagi-io/hyperon-experimental/issues/470

**Comment by luketpeterson** [comment] 2024-02-09 05:19
> My understanding that root cause is clear and this issue will be outdated by the merge of the module system. #470

Yes and yes.  But we could also drop in a hot-fix to get back module loading from .py files, to remain compatible with the behavior before https://github.com/trueagi-io/hyperon-experimental/pull/555  This hotfix would be aligned with the spirit of the module system since it will detect whether a module is a directory or a .py file, and does not require the .metta script to make a distinction.

**Comment by Necr0x0Der** [comment] 2024-02-09 06:35
It wouldn't be a hotfix as the new module system will not use `extend-py`, so people will still have to fix their scripts. No one asked for rolling back the behavior with loading .py files without extension which are not in PYTHONPATH

**Comment by vsbogd** [comment] 2024-02-28 08:18
My understanding now this issue is fixed, the following script works:
`random_binding.py`:
```
from hyperon.atoms import OperationAtom
from hyperon.ext import register_atoms
import random

@register_atoms
def my_atoms():
    return {
        'random': OperationAtom('random', random.random),
    }
```

`test.metta`:
```
!(import! &self random_binding)
; random will be executed, a1 is associated with the result
!(bind! a1 (random))
```

**Comment by vsbogd** [comment] 2024-02-28 08:23
> What was the issue with extend-py? It made it clear that a Python extension file is loaded instead of a MeTTa file, I don't consider using the same name for both to be a good idea (if that is the plan). 

@patham9 , I would suggest raising a separate issue to discuss  `extend-py!` advantages.

**Closed by vsbogd** 2024-02-28 08:23 UTC
Labels: bug
