### ISSUE TITLE
The presence of a function prevents another function from running

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#317] opened 2023-06-02 05:38 UTC
## What is the problem?

The presence of a function, `foo`, prevents another function, `bar`, from running properly, apparently because one of the arguments of `bar` unifies with the definition of `foo`. 

## How to reproduce it?

Run the following metta file (via `metta.py`)

```clojure
;; Define foo
(= (foo $x) $x)             ; prevents bar from running properly

;; Define bar
(: bar (-> Atom Atom Atom))
(= (bar $query $rule)
   (let* (((: $ructor (-> $premise $conclusion)) $rule)
          ((: ($ructor $proof) $conclusion) $query)
          ((: $proof $premise) (: a A)))
          $query))

;; Test bar
!(bar (: ($f a) B) (: f (-> A B)))
```

## What should normally be expected?

```clojure
[(: (f a) B)]
```

## What is output instead?

```clojure
[]
```

## Remark

If the definition of `foo` is removed then the output is the expected one.

**Comment by vsbogd** [comment] 2024-02-09 07:05
Looks like it is a duplicate of #242 , closing as now it works as expected.

**Closed by vsbogd** 2024-02-09 07:05 UTC
Labels: bug
