### ISSUE TITLE
Adding whitespace in string prints the quotes

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#112] opened 2022-06-17 08:02 UTC
Not sure it is a feature or a bug, but I noticed that strings inside metta are printed differently if they contain whitespaces or not.  For instance

```metta
!(println! ("alpha"))
!(println! ("alpha omega"))
```

outputs

```
(alpha)
("alpha omega")
```

Also, another issue, the following

```metta
!(println! "alpha")
```

prints nothing.  Again, I don't know if it's a feature or a bug.

**Comment by Necr0x0Der** [comment] 2022-06-17 08:33
Thanks. The problem with `!(println! "alpha")` is caused by the incomplete implementation of the latest approach to types on the Python side. `println!` expects the input argument type, which is not matched against grounded `String`. I'll fix this in a few days.

**Comment by Necr0x0Der** [comment] 2022-06-19 20:19
`!(println! "alpha")` should be fixed by #113 
As for `!(println! ("alpha omega"))`, this is a deeper problem. It seems that the parser splits "alpha omega" into two (non-grounded) atoms `S("alpha)` and `S(omega")`. While the regex expression for `String` seems to be correct, the parser applies it after splitting the string into two tokens by whitespace.

**Comment by vsbogd** [comment] 2022-06-20 11:39
Well, yes, I checked previous implementation, there it was possible to implement token which eats `".."` and represents it as an atom. In Rust version I didn't implemented it from very beginning because I was not sure how to implement it in Rust effectively. So for now it is not implemented but it is possible in principle.

**Comment by ngeiswei** [comment] 2022-07-07 04:28
FYI, with the latest revision d28dc6528ec1cd18a309007f8c81b907c5e5267b, I'm now get a crash when printing a single word:

```scheme
!(println! ("=== Test print ==="))
!(println! ("Test print"))
!(println! ("print"))
```

```
("=== Test print ===")
("Test print")
thread '<unnamed>' panicked at 'Trying to execute non executable atom', src/atom.rs:270:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
Aborted
```

**Comment by Necr0x0Der** [comment] 2022-07-07 07:41
It's because you are trying to execute a string - `("print")`. This will be fixed soon (execution of non-executable atoms, which are of non-arrow type, will just remain these atoms as they are). `!(println! ("=== Test print ==="))` works, because whitespaces are still not fixed, so it creates several symbolic atoms, which evaluation is done via pattern matching and doesn't cause Rust to panic.

**Comment by vsbogd** [comment] 2022-07-07 07:50
@ngeiswei it should be fixed by #133

**Comment by ngeiswei** [comment] 2022-07-07 09:20
It works, thanks!  Closing.

**Comment by ngeiswei** [comment] 2022-07-07 09:21
Oh, wait, maybe the entire issue hasn't been solved.  Reopening.

**Comment by vsbogd** [comment] 2022-07-07 09:30
> Oh, wait, maybe the entire issue hasn't been solved. Reopening.

Yes, sorry, I meant crash is fixed by #133

**Comment by vsbogd** [comment] 2022-08-03 08:14
I raised #151 which fixes this. 

It would be interesting to rework approach and allow injecting fully custom tokenizer into `SExprParser`. In current approach Rust tokenizer returns sequence of symbols between whitespaces and then checks if it is know to user defined tokenizer. We could give more flexibility to user defined tokenizer. We could define few standard tokens: `(`, `)`, whitespace, `$<name>`, and allow user's tokenizer to eat stream of chars and return next token: either grounded atom or symbol atom. It will allow defining new quoting syntax (for example using single quotes `'<string>'`).

**Closed** 2022-08-03 09:15 UTC
Labels: bug

**Comment by ngeiswei** [comment] 2022-08-04 05:58
I should mention though that
```scheme
!(== "A B" "A B")
```
still returns
```
[]
```
instead of
```scheme
[True]
```
It might a different issue, but I'm mentioning it here because @tanksha was referred to that issue when she pointed out that bug.

**Comment by Necr0x0Der** [comment] 2022-08-04 06:29
It returns `True` for me. If this is the first expression, please, try to add an empty line before. In some environments, I have an issue that Python adds a special symbol at the beginning of the file, which is glued with `!`.

**Comment by ngeiswei** [comment] 2022-08-04 07:51
It works!  I thought I was using the last revision and in fact I wasn't.
