### ISSUE TITLE
C interface does not build

### ISSUE THREAD

**Issue by gl-yziquel** [trueagi-io/hyperon-experimental#703] opened 2024-06-02 01:29 UTC
The C interface does not build. At least not out of the box. I followed the procedure on the README.md, and got this at the `make`step:

```console
----------------------------------------------------------------------
Libraries have been installed in:
   /home/mini-me/.conan/data/subunit/1.4.0/_/_/package/095274926d7784555b5378b8638d408c0c4d0378/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[4]: Leaving directory '/home/mini-me/.conan/data/subunit/1.4.0/_/_/build/095274926d7784555b5378b8638d408c0c4d0378'
make[3]: *** [Makefile:1447: install-am] Error 2
make[3]: Leaving directory '/home/mini-me/.conan/data/subunit/1.4.0/_/_/build/095274926d7784555b5378b8638d408c0c4d0378'
ERROR: subunit/1.4.0: Error in package() method, line 127
        autotools.install(args=install_args)
        ConanException: Error 2 while executing make install 'INSTALLARCHLIB=/home/mini-me/.conan/data/subunit/1.4.0/_/_/package/095274926d7784555b5378b8638d408c0c4d0378/lib' 'INSTALLSITEARCH=/home/mini-me/.conan/data/subunit/1.4.0/_/_/build/095274926d7784555b5378b8638d408c0c4d0378/archlib' 'INSTALLVENDORARCH=/home/mini-me/.conan/data/subunit/1.4.0/_/_/build/095274926d7784555b5378b8638d408c0c4d0378/archlib' 'INSTALLSITEBIN=/home/mini-me/.conan/data/subunit/1.4.0/_/_/package/095274926d7784555b5378b8638d408c0c4d0378/bin' 'INSTALLSITESCRIPT=/home/mini-me/.conan/data/subunit/1.4.0/_/_/package/095274926d7784555b5378b8638d408c0c4d0378/bin' 'INSTALLSITEMAN1DIR=/home/mini-me/.conan/data/subunit/1.4.0/_/_/build/095274926d7784555b5378b8638d408c0c4d0378/share/man/man1' 'INSTALLSITEMAN3DIR=/home/mini-me/.conan/data/subunit/1.4.0/_/_/build/095274926d7784555b5378b8638d408c0c4d0378/share/man/man3' -j32
CMake Error at CMakeLists.txt:14 (include):
  include could not find requested file:

    /home/mini-me/home/cellar/hyperon-experimental/build/hyperonc-prefix/src/hyperonc-build/conanbuildinfo.cmake


CMake Error at CMakeLists.txt:15 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".


-- Configuring incomplete, errors occurred!
make[2]: *** [CMakeFiles/hyperonc.dir/build.make:91: hyperonc-prefix/src/hyperonc-stamp/hyperonc-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/hyperonc.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

Built from git HEAD.

**Comment by gl-yziquel** [comment] 2024-06-02 03:05
Running conan in a 3.11.x python environment fixes the build and this issue.

Hence the PR.

**Comment by vsbogd** [comment] 2024-06-03 10:21
Seems to be a duplicate of #584 
@gl-yziquel  could you please attach the full log of the run to check?

**Comment by gl-yziquel** [comment] 2024-06-03 10:55
> Seems to be a duplicate of #584 @gl-yziquel could you please attach the full log of the run to check?

4389 lines of build log ?

**Comment by gl-yziquel** [comment] 2024-06-03 11:02
> You can attach it as a file if you want or just confirm it is a duplicate of the #584

Just the problem. I can't upload the file. It lives on a machine where I have restricted access. I'd have to use curl trickery with github's api to get it uploaded. It may take me quite some time till I get around to that.

**Comment by vsbogd** [comment] 2024-06-03 11:11
Closing as a duplicate of the #584 
@gl-yziquel please shout if you know it is not a case.

**Closed by vsbogd** 2024-06-03 11:11 UTC
