### ISSUE TITLE
Evaluating `<=` or `>=` raise error

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#489] opened 2023-11-07 08:22 UTC
## What is the problem?

Evaluating `<=` or `>=` raise error.

## How to reproduce the problem?

Evaluate

```
!(<= 0 1)
```

## What is output?

```
[(Error (<= 0.1 1.1) <= expects two number arguments)]
```

## What should normally be output?

```
[True]
```

## Remarks

Operator `>=` has the same problem, but `<` or `>` work normally.

**Comment by Necr0x0Der** [comment] 2023-11-07 08:24
Most likely, the issue is that `<=` and `>=` got implemented in Rust stdlib, but not in Python.

**Comment by Necr0x0Der** [comment] 2023-11-07 08:30
It might be a good first issue, but since it is marked as a blocker I created #490 . I'm not sure if it solves the issue, because I observe a little bit different behavior than described. Namely, `(<= 0 1)` is just not reduced (instead of raising the error). Thus, it seems there is some difference in environments. So, @ngeiswei , please check if it works.

**Comment by ngeiswei** [comment] 2023-11-07 08:44
Thanks for being so reactive, @Necr0x0Der.  Yes the problem is on the rust end, but I could not figure what.  Your quick fix works however, so I'm going to use that for now and I'll let it to you and @vsbogd to decide what is a proper longer-term fix.

**Comment by Necr0x0Der** [comment] 2023-11-07 08:55
Could you please describe the environment, in which you got it. Was it a purely Rust version? It looks like that in your case `>=` was from Rust, while numbers where from Python. If so, it is not a Rust problem per se (and not a bug at all), but the question remains what to do with different versions of grounded atoms in different host languages.
But I still wonder how you got the error. It might be an issue for a specific environment meaning that some Rust tokens are loaded, which are language-specific and should not be loaded in presence of Python support.

**Comment by ngeiswei** [comment] 2023-11-07 09:03
* hyperon-experimental 21dbd82
* Python 3.9.2
* rustup 1.26.0
* cargo 1.73.0
* rustc 1.73.0

Anything else you need?

**Comment by ngeiswei** [comment] 2023-11-07 09:11
It was running from the `metta` command line interpreter, if that is what you were asking.

**Comment by Necr0x0Der** [comment] 2023-11-07 09:15
> It was running from the metta command line interpreter, if that is what you were asking.

Yes, I guessed so. Thus, this reveals that there is some difference in the behavior of running scripts from REPL and from Python runner. I don't think this difference is critical, but I'd like to hear some thoughts from @luketpeterson .

**Comment by vsbogd** [comment] 2024-02-08 21:46
Moved these operations into a Rust stdlib in https://github.com/trueagi-io/hyperon-experimental/pull/462

**Closed by vsbogd** 2024-02-08 21:46 UTC
Labels: bug, good first issue
