### ISSUE TITLE
foldl randomly fails

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#484] opened 2023-11-02 19:12 UTC
This program occasionaly gives wrong result:
```
        (= (all $A)
           (foldl-atom $A True $a $b (eval (and $a $b))))
        !(all (True True True False))
```
[(foldl-atom (True True True False) True $head#1623 $b#1168 (eval (and $a#1167 $head#1677)))]

3/4 of runs i get correct result [[False]] and 1/4 the expression above

debug logs
[log_debug.txt](https://github.com/trueagi-io/hyperon-experimental/files/13243607/log_debug.txt)

interpreter steps
[log.txt](https://github.com/trueagi-io/hyperon-experimental/files/13243620/log.txt)

**Comment by Necr0x0Der** [comment] 2023-11-22 16:01
Is it related to #461 ?

**Comment by vsbogd** [comment] 2023-12-05 15:37
I believe here @noskill means minimal MeTTa interpreter and it is different from one which is mentioned in #461

**Comment by vsbogd** [comment] 2023-12-05 15:39
on the other hand the root cause may be deeper, for instance in `Bindings` implementation

**Comment by vsbogd** [comment] 2024-02-08 21:42
Should be fixed now, I cannot reproduce. @noskill could you please retest and close?

**Closed** 2024-03-14 07:14 UTC
Labels: bug

**Comment by noskill** [comment] 2024-03-18 08:48
Yes, i can't reproduce it anymore.
