### ISSUE TITLE
Absence of information about REPL (building and usage) in README.md

### ISSUE THREAD

**Issue by astroseger** [trueagi-io/hyperon-experimental#560] opened 2024-01-31 11:54 UTC
There is no information about REPL in README.md. Probably we should add information about building of REPL and some basic information about usage.

**Comment by vsbogd** [comment] 2024-02-02 03:30
@astroseger I am sorry, I know I asked you to open the issue but it turned out we already have one. Closing it as a duplicate of https://github.com/trueagi-io/hyperon-experimental/issues/428

**Closed by vsbogd** 2024-02-02 03:30 UTC
